const {chromium}=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8005/admin/login');
 await page.locator('[name=email]').fill('admin@uecfi.local');await page.locator('[name=password]').fill(process.env.CMS_TEST_PASSWORD);
 await page.getByRole('button',{name:'Sign in'}).click();await page.waitForURL('**/admin');
 await page.goto('http://127.0.0.1:8005/admin/media');
 await page.locator('[name="images[]"]').setInputFiles(['public/images/uecfi-logo.png','public/images/landscape.jpg']);
 await page.locator('[name=alt]').fill('Browser verification image');
 await page.getByRole('button',{name:'Upload images'}).click();
 await page.waitForURL('**/admin/media');
 const mediaIds=await page.locator('.media-library article small').allTextContents();
 const ids=mediaIds.map(s=>s.match(/\d+/)[0]);
 assert.ok(ids.length>=2);
 await page.goto('http://127.0.0.1:8005/admin/content/activities/create');
 await page.locator('[name=title]').fill('Browser verification activity');
 await page.locator('[name=excerpt]').fill('Temporary browser verification.');
 await page.locator('[name=content]').fill('A temporary record used to verify the full CMS flow.');
 await page.locator('[name=status]').selectOption('published');
 await page.locator('[name=cover_id]').selectOption(ids[0]);
 await page.locator('[name="gallery[]"]').nth(0).check();await page.locator('[name="gallery[]"]').nth(1).check();
 await page.getByRole('button',{name:'Save changes'}).click();await page.waitForURL('**/edit');
 const editUrl=page.url();
 assert.ok(await page.locator('.toast').isVisible());
 const publicPage=await context.newPage();
 await publicPage.goto('http://127.0.0.1:8005/activities/browser-verification-activity');
 assert.equal(await publicPage.locator('.gallery-image').count(),2);
 await publicPage.locator('.gallery-image').first().click();
 assert.equal(await publicPage.locator('#lightbox[open]').count(),1);
 await publicPage.getByRole('button',{name:'Next image'}).click();
 assert.match(await publicPage.locator('.gallery-counter').textContent(),/2 \/ 2/);
 await publicPage.keyboard.press('ArrowLeft');assert.match(await publicPage.locator('.gallery-counter').textContent(),/1 \/ 2/);
 await publicPage.keyboard.press('Escape');assert.equal(await publicPage.locator('#lightbox[open]').count(),0);
 await page.locator('[name=status]').selectOption('draft');await page.getByRole('button',{name:'Save changes'}).click();await page.waitForURL(editUrl);
 assert.equal((await publicPage.reload()).status(),404);
 await page.goto('http://127.0.0.1:8005/admin/content/activities');
 const row=page.locator('tr').filter({hasText:'Browser verification activity'});
 await row.getByRole('button',{name:'Delete',exact:true}).click();
 assert.equal(await page.locator('#delete-confirm[open]').count(),1);
 await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await row.count(),1);
 await row.getByRole('button',{name:'Delete',exact:true}).click();
 await page.locator('#delete-confirm [data-confirm]').click();
 await page.waitForURL('**/admin/content/activities');assert.equal(await page.locator('tr').filter({hasText:'Browser verification activity'}).count(),0);
 await page.goto('http://127.0.0.1:8005/admin/media');
 for(const id of ids.slice(0,2)){
  const card=page.locator('.media-library article').filter({has:page.locator('small',{hasText:'Media ID '+id})});
  await card.getByRole('button',{name:'Delete',exact:true}).click();await page.locator('#delete-confirm [data-confirm]').click();await page.waitForURL('**/admin/media');
 }
 await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:8005/admin');
 await page.locator('.admin-menu').click();assert.equal(await page.locator('#admin-navigation').isVisible(),true);
 await page.locator('.admin-menu').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'storage/app/private/admin-mobile.png',fullPage:true});
 await page.goto('http://127.0.0.1:8005/admin/account');assert.equal(await page.locator('[name=current_password]').count(),1);
 await page.locator('.admin-menu').click();await page.getByRole('button',{name:'Log out'}).click();await page.waitForURL('http://127.0.0.1:8005/');
 await page.goto('http://127.0.0.1:8005/admin');await page.waitForURL('**/admin/login');
 const csrf=await context.request.post('http://127.0.0.1:8005/admin/login',{form:{email:'admin@uecfi.local',password:'invalid'}});
 assert.equal(csrf.status(),419);
 const nojs=await browser.newContext({javaScriptEnabled:false});
 const plain=await nojs.newPage();await plain.goto('http://127.0.0.1:8005/');
 assert.ok(await plain.locator('h1').isVisible());assert.ok(await plain.locator('#splash').isHidden());
 console.log(JSON.stringify({crud:true,upload:true,gallery:true,deleteConfirmation:true,unpublish:true,mobileAdmin:true,logout:true,csrf:419,noJavaScript:true,errors}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
