const { chromium } = require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const response=await page.goto('http://127.0.0.1:8005/',{waitUntil:'networkidle'});
await page.waitForTimeout(5300);
await page.screenshot({path:'storage/app/private/home-desktop.png',fullPage:false});
console.log(JSON.stringify({status:response.status(),title:await page.title(),splashHidden:await page.locator('#splash').isHidden(),overflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),errors}));
await page.evaluate(()=>window.scrollTo(0,900));await page.waitForTimeout(900);
await page.screenshot({path:'storage/app/private/home-sections.png'});
await page.goto('http://127.0.0.1:8005/admin/login');
await page.locator('[name=email]').fill('admin@uecfi.local');
await page.locator('[name=password]').fill(process.env.CMS_TEST_PASSWORD);
await page.getByRole('button',{name:'Sign in'}).click();
await page.waitForURL('**/admin');await page.screenshot({path:'storage/app/private/admin-desktop.png',fullPage:true});
console.log(JSON.stringify({admin:page.url(),dashboard:await page.locator('h1').innerText()}));
await page.goto('http://127.0.0.1:8005/admin/settings/home');await page.waitForTimeout(1200);
await page.locator('[name=hero_heading]').fill('Preview works.');
console.log(JSON.stringify({preview:await page.frameLocator('#site-preview').locator('.hero h1').innerText()}));
await page.screenshot({path:'storage/app/private/editor-desktop.png',fullPage:false});
const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});
mobile.on('pageerror',e=>errors.push(e.message));
await mobile.goto('http://127.0.0.1:8005/',{waitUntil:'networkidle'});await mobile.screenshot({path:'storage/app/private/home-mobile.png',fullPage:true});
await mobile.getByRole('button',{name:'Open navigation'}).click();
await mobile.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Officers',exact:true}).click();
await mobile.waitForURL('**/officers');await mobile.locator('.officer-open').first().click();
console.log(JSON.stringify({mobileOverflow:await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),profileModal:await mobile.locator('dialog[open]').count(),errors}));
await mobile.keyboard.press('Escape');
await mobile.screenshot({path:'storage/app/private/officers-mobile.png',fullPage:true});
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
